// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inputmessage.proto

package org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor;

public final class CarDataProto {
  private CarDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.sjtu.se.ipads.fdbserver.dataprocessor.CarData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 carID = 1;</code>
     * @return The carID.
     */
    int getCarID();

    /**
     * <code>uint32 x = 2;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>uint32 y = 3;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>uint32 v_x = 4;</code>
     * @return The vX.
     */
    int getVX();

    /**
     * <code>uint32 v_y = 5;</code>
     * @return The vY.
     */
    int getVY();

    /**
     * <code>uint32 v_r = 6;</code>
     * @return The vR.
     */
    int getVR();

    /**
     * <code>uint32 direction = 7;</code>
     * @return The direction.
     */
    int getDirection();

    /**
     * <code>string img = 8;</code>
     * @return The img.
     */
    java.lang.String getImg();
    /**
     * <code>string img = 8;</code>
     * @return The bytes for img.
     */
    com.google.protobuf.ByteString
        getImgBytes();
  }
  /**
   * Protobuf type {@code org.sjtu.se.ipads.fdbserver.dataprocessor.CarData}
   */
  public static final class CarData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.sjtu.se.ipads.fdbserver.dataprocessor.CarData)
      CarDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarData.newBuilder() to construct.
    private CarData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarData() {
      img_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CarData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              carID_ = input.readUInt32();
              break;
            }
            case 16: {

              x_ = input.readUInt32();
              break;
            }
            case 24: {

              y_ = input.readUInt32();
              break;
            }
            case 32: {

              vX_ = input.readUInt32();
              break;
            }
            case 40: {

              vY_ = input.readUInt32();
              break;
            }
            case 48: {

              vR_ = input.readUInt32();
              break;
            }
            case 56: {

              direction_ = input.readUInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              img_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CarDataProto.internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CarDataProto.internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CarDataProto.CarData.class, CarDataProto.CarData.Builder.class);
    }

    public static final int CARID_FIELD_NUMBER = 1;
    private int carID_;
    /**
     * <code>uint32 carID = 1;</code>
     * @return The carID.
     */
    @java.lang.Override
    public int getCarID() {
      return carID_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private int x_;
    /**
     * <code>uint32 x = 2;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private int y_;
    /**
     * <code>uint32 y = 3;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int V_X_FIELD_NUMBER = 4;
    private int vX_;
    /**
     * <code>uint32 v_x = 4;</code>
     * @return The vX.
     */
    @java.lang.Override
    public int getVX() {
      return vX_;
    }

    public static final int V_Y_FIELD_NUMBER = 5;
    private int vY_;
    /**
     * <code>uint32 v_y = 5;</code>
     * @return The vY.
     */
    @java.lang.Override
    public int getVY() {
      return vY_;
    }

    public static final int V_R_FIELD_NUMBER = 6;
    private int vR_;
    /**
     * <code>uint32 v_r = 6;</code>
     * @return The vR.
     */
    @java.lang.Override
    public int getVR() {
      return vR_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 7;
    private int direction_;
    /**
     * <code>uint32 direction = 7;</code>
     * @return The direction.
     */
    @java.lang.Override
    public int getDirection() {
      return direction_;
    }

    public static final int IMG_FIELD_NUMBER = 8;
    private volatile java.lang.Object img_;
    /**
     * <code>string img = 8;</code>
     * @return The img.
     */
    @java.lang.Override
    public java.lang.String getImg() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        img_ = s;
        return s;
      }
    }
    /**
     * <code>string img = 8;</code>
     * @return The bytes for img.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImgBytes() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (carID_ != 0) {
        output.writeUInt32(1, carID_);
      }
      if (x_ != 0) {
        output.writeUInt32(2, x_);
      }
      if (y_ != 0) {
        output.writeUInt32(3, y_);
      }
      if (vX_ != 0) {
        output.writeUInt32(4, vX_);
      }
      if (vY_ != 0) {
        output.writeUInt32(5, vY_);
      }
      if (vR_ != 0) {
        output.writeUInt32(6, vR_);
      }
      if (direction_ != 0) {
        output.writeUInt32(7, direction_);
      }
      if (!getImgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, img_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (carID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, carID_);
      }
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, y_);
      }
      if (vX_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, vX_);
      }
      if (vY_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, vY_);
      }
      if (vR_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, vR_);
      }
      if (direction_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, direction_);
      }
      if (!getImgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, img_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CarDataProto.CarData)) {
        return super.equals(obj);
      }
      CarDataProto.CarData other = (CarDataProto.CarData) obj;

      if (getCarID()
          != other.getCarID()) return false;
      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (getVX()
          != other.getVX()) return false;
      if (getVY()
          != other.getVY()) return false;
      if (getVR()
          != other.getVR()) return false;
      if (getDirection()
          != other.getDirection()) return false;
      if (!getImg()
          .equals(other.getImg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CARID_FIELD_NUMBER;
      hash = (53 * hash) + getCarID();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + V_X_FIELD_NUMBER;
      hash = (53 * hash) + getVX();
      hash = (37 * hash) + V_Y_FIELD_NUMBER;
      hash = (53 * hash) + getVY();
      hash = (37 * hash) + V_R_FIELD_NUMBER;
      hash = (53 * hash) + getVR();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getDirection();
      hash = (37 * hash) + IMG_FIELD_NUMBER;
      hash = (53 * hash) + getImg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CarDataProto.CarData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarDataProto.CarData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarDataProto.CarData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarDataProto.CarData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarDataProto.CarData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CarDataProto.CarData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CarDataProto.CarData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CarDataProto.CarData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CarDataProto.CarData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CarDataProto.CarData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CarDataProto.CarData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CarDataProto.CarData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CarDataProto.CarData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.sjtu.se.ipads.fdbserver.dataprocessor.CarData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.sjtu.se.ipads.fdbserver.dataprocessor.CarData)
        CarDataProto.CarDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CarDataProto.internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CarDataProto.internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CarDataProto.CarData.class, CarDataProto.CarData.Builder.class);
      }

      // Construct using CarDataProto.CarData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        carID_ = 0;

        x_ = 0;

        y_ = 0;

        vX_ = 0;

        vY_ = 0;

        vR_ = 0;

        direction_ = 0;

        img_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CarDataProto.internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor;
      }

      @java.lang.Override
      public CarDataProto.CarData getDefaultInstanceForType() {
        return CarDataProto.CarData.getDefaultInstance();
      }

      @java.lang.Override
      public CarDataProto.CarData build() {
        CarDataProto.CarData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CarDataProto.CarData buildPartial() {
        CarDataProto.CarData result = new CarDataProto.CarData(this);
        result.carID_ = carID_;
        result.x_ = x_;
        result.y_ = y_;
        result.vX_ = vX_;
        result.vY_ = vY_;
        result.vR_ = vR_;
        result.direction_ = direction_;
        result.img_ = img_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CarDataProto.CarData) {
          return mergeFrom((CarDataProto.CarData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CarDataProto.CarData other) {
        if (other == CarDataProto.CarData.getDefaultInstance()) return this;
        if (other.getCarID() != 0) {
          setCarID(other.getCarID());
        }
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getVX() != 0) {
          setVX(other.getVX());
        }
        if (other.getVY() != 0) {
          setVY(other.getVY());
        }
        if (other.getVR() != 0) {
          setVR(other.getVR());
        }
        if (other.getDirection() != 0) {
          setDirection(other.getDirection());
        }
        if (!other.getImg().isEmpty()) {
          img_ = other.img_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CarDataProto.CarData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CarDataProto.CarData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int carID_ ;
      /**
       * <code>uint32 carID = 1;</code>
       * @return The carID.
       */
      @java.lang.Override
      public int getCarID() {
        return carID_;
      }
      /**
       * <code>uint32 carID = 1;</code>
       * @param value The carID to set.
       * @return This builder for chaining.
       */
      public Builder setCarID(int value) {

        carID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 carID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCarID() {

        carID_ = 0;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>uint32 x = 2;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>uint32 x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {

        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {

        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>uint32 y = 3;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>uint32 y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {

        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {

        y_ = 0;
        onChanged();
        return this;
      }

      private int vX_ ;
      /**
       * <code>uint32 v_x = 4;</code>
       * @return The vX.
       */
      @java.lang.Override
      public int getVX() {
        return vX_;
      }
      /**
       * <code>uint32 v_x = 4;</code>
       * @param value The vX to set.
       * @return This builder for chaining.
       */
      public Builder setVX(int value) {

        vX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 v_x = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearVX() {

        vX_ = 0;
        onChanged();
        return this;
      }

      private int vY_ ;
      /**
       * <code>uint32 v_y = 5;</code>
       * @return The vY.
       */
      @java.lang.Override
      public int getVY() {
        return vY_;
      }
      /**
       * <code>uint32 v_y = 5;</code>
       * @param value The vY to set.
       * @return This builder for chaining.
       */
      public Builder setVY(int value) {

        vY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 v_y = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVY() {

        vY_ = 0;
        onChanged();
        return this;
      }

      private int vR_ ;
      /**
       * <code>uint32 v_r = 6;</code>
       * @return The vR.
       */
      @java.lang.Override
      public int getVR() {
        return vR_;
      }
      /**
       * <code>uint32 v_r = 6;</code>
       * @param value The vR to set.
       * @return This builder for chaining.
       */
      public Builder setVR(int value) {

        vR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 v_r = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVR() {

        vR_ = 0;
        onChanged();
        return this;
      }

      private int direction_ ;
      /**
       * <code>uint32 direction = 7;</code>
       * @return The direction.
       */
      @java.lang.Override
      public int getDirection() {
        return direction_;
      }
      /**
       * <code>uint32 direction = 7;</code>
       * @param value The direction to set.
       * @return This builder for chaining.
       */
      public Builder setDirection(int value) {

        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 direction = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirection() {

        direction_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object img_ = "";
      /**
       * <code>string img = 8;</code>
       * @return The img.
       */
      public java.lang.String getImg() {
        java.lang.Object ref = img_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string img = 8;</code>
       * @return The bytes for img.
       */
      public com.google.protobuf.ByteString
          getImgBytes() {
        java.lang.Object ref = img_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          img_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string img = 8;</code>
       * @param value The img to set.
       * @return This builder for chaining.
       */
      public Builder setImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        img_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string img = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearImg() {

        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      /**
       * <code>string img = 8;</code>
       * @param value The bytes for img to set.
       * @return This builder for chaining.
       */
      public Builder setImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        img_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.sjtu.se.ipads.fdbserver.dataprocessor.CarData)
    }

    // @@protoc_insertion_point(class_scope:org.sjtu.se.ipads.fdbserver.dataprocessor.CarData)
    private static final CarDataProto.CarData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CarDataProto.CarData();
    }

    public static CarDataProto.CarData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarData>
        PARSER = new com.google.protobuf.AbstractParser<CarData>() {
      @java.lang.Override
      public CarData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CarDataProto.CarData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022inputmessage.proto\022)org.sjtu.se.ipads." +
      "fdbserver.dataprocessor\"u\n\007CarData\022\r\n\005ca" +
      "rID\030\001 \001(\r\022\t\n\001x\030\002 \001(\r\022\t\n\001y\030\003 \001(\r\022\013\n\003v_x\030\004" +
      " \001(\r\022\013\n\003v_y\030\005 \001(\r\022\013\n\003v_r\030\006 \001(\r\022\021\n\tdirect" +
      "ion\030\007 \001(\r\022\013\n\003img\030\010 \001(\tB9\n)org.sjtu.se.ip" +
      "ads.fdbserver.dataprocessorB\014CarDataProt" +
      "ob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sjtu_se_ipads_fdbserver_dataprocessor_CarData_descriptor,
        new java.lang.String[] { "CarID", "X", "Y", "VX", "VY", "VR", "Direction", "Img", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
