// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fieldMessage.proto

package org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor;

public final class fieldProto {
  private fieldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface fieldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 delta = 1;</code>
     * @return The delta.
     */
    int getDelta();

    /**
     * <code>uint32 fieldValue = 2;</code>
     * @return The fieldValue.
     */
    int getFieldValue();
  }
  /**
   * Protobuf type {@code org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field}
   */
  public static final class field extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field)
      fieldOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use field.newBuilder() to construct.
    private field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private field() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new field();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private field(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              delta_ = input.readUInt32();
              break;
            }
            case 16: {

              fieldValue_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.class, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder.class);
    }

    public static final int DELTA_FIELD_NUMBER = 1;
    private int delta_;
    /**
     * <code>uint32 delta = 1;</code>
     * @return The delta.
     */
    @java.lang.Override
    public int getDelta() {
      return delta_;
    }

    public static final int FIELDVALUE_FIELD_NUMBER = 2;
    private int fieldValue_;
    /**
     * <code>uint32 fieldValue = 2;</code>
     * @return The fieldValue.
     */
    @java.lang.Override
    public int getFieldValue() {
      return fieldValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (delta_ != 0) {
        output.writeUInt32(1, delta_);
      }
      if (fieldValue_ != 0) {
        output.writeUInt32(2, fieldValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (delta_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, delta_);
      }
      if (fieldValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, fieldValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field)) {
        return super.equals(obj);
      }
      org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field other = (org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field) obj;

      if (getDelta()
          != other.getDelta()) return false;
      if (getFieldValue()
          != other.getFieldValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DELTA_FIELD_NUMBER;
      hash = (53 * hash) + getDelta();
      hash = (37 * hash) + FIELDVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFieldValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field)
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.class, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder.class);
      }

      // Construct using org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        delta_ = 0;

        fieldValue_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor;
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getDefaultInstanceForType() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.getDefaultInstance();
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field build() {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field buildPartial() {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field result = new org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field(this);
        result.delta_ = delta_;
        result.fieldValue_ = fieldValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field) {
          return mergeFrom((org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field other) {
        if (other == org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.getDefaultInstance()) return this;
        if (other.getDelta() != 0) {
          setDelta(other.getDelta());
        }
        if (other.getFieldValue() != 0) {
          setFieldValue(other.getFieldValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int delta_ ;
      /**
       * <code>uint32 delta = 1;</code>
       * @return The delta.
       */
      @java.lang.Override
      public int getDelta() {
        return delta_;
      }
      /**
       * <code>uint32 delta = 1;</code>
       * @param value The delta to set.
       * @return This builder for chaining.
       */
      public Builder setDelta(int value) {
        
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 delta = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelta() {
        
        delta_ = 0;
        onChanged();
        return this;
      }

      private int fieldValue_ ;
      /**
       * <code>uint32 fieldValue = 2;</code>
       * @return The fieldValue.
       */
      @java.lang.Override
      public int getFieldValue() {
        return fieldValue_;
      }
      /**
       * <code>uint32 fieldValue = 2;</code>
       * @param value The fieldValue to set.
       * @return This builder for chaining.
       */
      public Builder setFieldValue(int value) {
        
        fieldValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fieldValue = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldValue() {
        
        fieldValue_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field)
    }

    // @@protoc_insertion_point(class_scope:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field)
    private static final org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field();
    }

    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<field>
        PARSER = new com.google.protobuf.AbstractParser<field>() {
      @java.lang.Override
      public field parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new field(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<field> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<field> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface fieldListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> 
        getFieldListList();
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getFieldList(int index);
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    int getFieldListCount();
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    java.util.List<? extends org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder> 
        getFieldListOrBuilderList();
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder getFieldListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList}
   */
  public static final class fieldList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList)
      fieldListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use fieldList.newBuilder() to construct.
    private fieldList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private fieldList() {
      fieldList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new fieldList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private fieldList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                fieldList_ = new java.util.ArrayList<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field>();
                mutable_bitField0_ |= 0x00000001;
              }
              fieldList_.add(
                  input.readMessage(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          fieldList_ = java.util.Collections.unmodifiableList(fieldList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.class, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.Builder.class);
    }

    public static final int FIELDLIST_FIELD_NUMBER = 1;
    private java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> fieldList_;
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> getFieldListList() {
      return fieldList_;
    }
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder> 
        getFieldListOrBuilderList() {
      return fieldList_;
    }
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    @java.lang.Override
    public int getFieldListCount() {
      return fieldList_.size();
    }
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    @java.lang.Override
    public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getFieldList(int index) {
      return fieldList_.get(index);
    }
    /**
     * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
     */
    @java.lang.Override
    public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder getFieldListOrBuilder(
        int index) {
      return fieldList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < fieldList_.size(); i++) {
        output.writeMessage(1, fieldList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < fieldList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, fieldList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList)) {
        return super.equals(obj);
      }
      org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList other = (org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList) obj;

      if (!getFieldListList()
          .equals(other.getFieldListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFieldListCount() > 0) {
        hash = (37 * hash) + FIELDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getFieldListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList)
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.class, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.Builder.class);
      }

      // Construct using org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFieldListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fieldListBuilder_ == null) {
          fieldList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fieldListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor;
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList getDefaultInstanceForType() {
        return org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.getDefaultInstance();
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList build() {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList buildPartial() {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList result = new org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList(this);
        int from_bitField0_ = bitField0_;
        if (fieldListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            fieldList_ = java.util.Collections.unmodifiableList(fieldList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.fieldList_ = fieldList_;
        } else {
          result.fieldList_ = fieldListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList) {
          return mergeFrom((org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList other) {
        if (other == org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList.getDefaultInstance()) return this;
        if (fieldListBuilder_ == null) {
          if (!other.fieldList_.isEmpty()) {
            if (fieldList_.isEmpty()) {
              fieldList_ = other.fieldList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldListIsMutable();
              fieldList_.addAll(other.fieldList_);
            }
            onChanged();
          }
        } else {
          if (!other.fieldList_.isEmpty()) {
            if (fieldListBuilder_.isEmpty()) {
              fieldListBuilder_.dispose();
              fieldListBuilder_ = null;
              fieldList_ = other.fieldList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFieldListFieldBuilder() : null;
            } else {
              fieldListBuilder_.addAllMessages(other.fieldList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> fieldList_ =
        java.util.Collections.emptyList();
      private void ensureFieldListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          fieldList_ = new java.util.ArrayList<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field>(fieldList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder> fieldListBuilder_;

      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> getFieldListList() {
        if (fieldListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fieldList_);
        } else {
          return fieldListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public int getFieldListCount() {
        if (fieldListBuilder_ == null) {
          return fieldList_.size();
        } else {
          return fieldListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field getFieldList(int index) {
        if (fieldListBuilder_ == null) {
          return fieldList_.get(index);
        } else {
          return fieldListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder setFieldList(
          int index, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field value) {
        if (fieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldListIsMutable();
          fieldList_.set(index, value);
          onChanged();
        } else {
          fieldListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder setFieldList(
          int index, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder builderForValue) {
        if (fieldListBuilder_ == null) {
          ensureFieldListIsMutable();
          fieldList_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder addFieldList(org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field value) {
        if (fieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldListIsMutable();
          fieldList_.add(value);
          onChanged();
        } else {
          fieldListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder addFieldList(
          int index, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field value) {
        if (fieldListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldListIsMutable();
          fieldList_.add(index, value);
          onChanged();
        } else {
          fieldListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder addFieldList(
          org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder builderForValue) {
        if (fieldListBuilder_ == null) {
          ensureFieldListIsMutable();
          fieldList_.add(builderForValue.build());
          onChanged();
        } else {
          fieldListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder addFieldList(
          int index, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder builderForValue) {
        if (fieldListBuilder_ == null) {
          ensureFieldListIsMutable();
          fieldList_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder addAllFieldList(
          java.lang.Iterable<? extends org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field> values) {
        if (fieldListBuilder_ == null) {
          ensureFieldListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, fieldList_);
          onChanged();
        } else {
          fieldListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder clearFieldList() {
        if (fieldListBuilder_ == null) {
          fieldList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public Builder removeFieldList(int index) {
        if (fieldListBuilder_ == null) {
          ensureFieldListIsMutable();
          fieldList_.remove(index);
          onChanged();
        } else {
          fieldListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder getFieldListBuilder(
          int index) {
        return getFieldListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder getFieldListOrBuilder(
          int index) {
        if (fieldListBuilder_ == null) {
          return fieldList_.get(index);  } else {
          return fieldListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public java.util.List<? extends org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder> 
           getFieldListOrBuilderList() {
        if (fieldListBuilder_ != null) {
          return fieldListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fieldList_);
        }
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder addFieldListBuilder() {
        return getFieldListFieldBuilder().addBuilder(
            org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.getDefaultInstance());
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder addFieldListBuilder(
          int index) {
        return getFieldListFieldBuilder().addBuilder(
            index, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.getDefaultInstance());
      }
      /**
       * <code>repeated .org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.field fieldList = 1;</code>
       */
      public java.util.List<org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder> 
           getFieldListBuilderList() {
        return getFieldListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder> 
          getFieldListFieldBuilder() {
        if (fieldListBuilder_ == null) {
          fieldListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.field.Builder, org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldOrBuilder>(
                  fieldList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          fieldList_ = null;
        }
        return fieldListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList)
    }

    // @@protoc_insertion_point(class_scope:org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldList)
    private static final org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList();
    }

    public static org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<fieldList>
        PARSER = new com.google.protobuf.AbstractParser<fieldList>() {
      @java.lang.Override
      public fieldList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new fieldList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<fieldList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<fieldList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sjtu.se.ipads.fdbserver.tsdb.dataprocessor.fieldProto.fieldList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022fieldMessage.proto\022.org.sjtu.se.ipads." +
      "fdbserver.tsdb.dataprocessor\"*\n\005field\022\r\n" +
      "\005delta\030\001 \001(\r\022\022\n\nfieldValue\030\002 \001(\r\"U\n\tfiel" +
      "dList\022H\n\tfieldList\030\001 \003(\01325.org.sjtu.se.i" +
      "pads.fdbserver.tsdb.dataprocessor.fieldB" +
      "<\n.org.sjtu.se.ipads.fdbserver.tsdb.data" +
      "processorB\nfieldProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_field_descriptor,
        new java.lang.String[] { "Delta", "FieldValue", });
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_sjtu_se_ipads_fdbserver_tsdb_dataprocessor_fieldList_descriptor,
        new java.lang.String[] { "FieldList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
