// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FieldMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FieldMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_FieldMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_FieldMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FieldMessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FieldMessage_2eproto;
namespace FieldMessage {
class IntField;
class IntFieldDefaultTypeInternal;
extern IntFieldDefaultTypeInternal _IntField_default_instance_;
class IntFieldList;
class IntFieldListDefaultTypeInternal;
extern IntFieldListDefaultTypeInternal _IntFieldList_default_instance_;
class StrField;
class StrFieldDefaultTypeInternal;
extern StrFieldDefaultTypeInternal _StrField_default_instance_;
class StrFieldList;
class StrFieldListDefaultTypeInternal;
extern StrFieldListDefaultTypeInternal _StrFieldList_default_instance_;
}  // namespace FieldMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::FieldMessage::IntField* Arena::CreateMaybeMessage<::FieldMessage::IntField>(Arena*);
template<> ::FieldMessage::IntFieldList* Arena::CreateMaybeMessage<::FieldMessage::IntFieldList>(Arena*);
template<> ::FieldMessage::StrField* Arena::CreateMaybeMessage<::FieldMessage::StrField>(Arena*);
template<> ::FieldMessage::StrFieldList* Arena::CreateMaybeMessage<::FieldMessage::StrFieldList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace FieldMessage {

// ===================================================================

class IntFieldList :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:FieldMessage.IntFieldList) */ {
 public:
  IntFieldList();
  virtual ~IntFieldList();

  IntFieldList(const IntFieldList& from);
  IntFieldList(IntFieldList&& from) noexcept
    : IntFieldList() {
    *this = ::std::move(from);
  }

  inline IntFieldList& operator=(const IntFieldList& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntFieldList& operator=(IntFieldList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IntFieldList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IntFieldList* internal_default_instance() {
    return reinterpret_cast<const IntFieldList*>(
               &_IntFieldList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IntFieldList& a, IntFieldList& b) {
    a.Swap(&b);
  }
  inline void Swap(IntFieldList* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IntFieldList* New() const final {
    return CreateMaybeMessage<IntFieldList>(nullptr);
  }

  IntFieldList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IntFieldList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IntFieldList& from);
  void MergeFrom(const IntFieldList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntFieldList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FieldMessage.IntFieldList";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_FieldMessage_2eproto);
    return ::descriptor_table_FieldMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldListFieldNumber = 1,
  };
  // repeated .FieldMessage.IntField fieldList = 1;
  int fieldlist_size() const;
  private:
  int _internal_fieldlist_size() const;
  public:
  void clear_fieldlist();
  ::FieldMessage::IntField* mutable_fieldlist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::IntField >*
      mutable_fieldlist();
  private:
  const ::FieldMessage::IntField& _internal_fieldlist(int index) const;
  ::FieldMessage::IntField* _internal_add_fieldlist();
  public:
  const ::FieldMessage::IntField& fieldlist(int index) const;
  ::FieldMessage::IntField* add_fieldlist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::IntField >&
      fieldlist() const;

  // @@protoc_insertion_point(class_scope:FieldMessage.IntFieldList)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::IntField > fieldlist_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FieldMessage_2eproto;
};
// -------------------------------------------------------------------

class IntField :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:FieldMessage.IntField) */ {
 public:
  IntField();
  virtual ~IntField();

  IntField(const IntField& from);
  IntField(IntField&& from) noexcept
    : IntField() {
    *this = ::std::move(from);
  }

  inline IntField& operator=(const IntField& from) {
    CopyFrom(from);
    return *this;
  }
  inline IntField& operator=(IntField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IntField& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IntField* internal_default_instance() {
    return reinterpret_cast<const IntField*>(
               &_IntField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IntField& a, IntField& b) {
    a.Swap(&b);
  }
  inline void Swap(IntField* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IntField* New() const final {
    return CreateMaybeMessage<IntField>(nullptr);
  }

  IntField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IntField>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IntField& from);
  void MergeFrom(const IntField& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IntField* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FieldMessage.IntField";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_FieldMessage_2eproto);
    return ::descriptor_table_FieldMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeltaFieldNumber = 1,
    kFieldValueFieldNumber = 2,
  };
  // uint32 delta = 1;
  void clear_delta();
  ::PROTOBUF_NAMESPACE_ID::uint32 delta() const;
  void set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_delta() const;
  void _internal_set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 fieldValue = 2;
  void clear_fieldvalue();
  ::PROTOBUF_NAMESPACE_ID::uint32 fieldvalue() const;
  void set_fieldvalue(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fieldvalue() const;
  void _internal_set_fieldvalue(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:FieldMessage.IntField)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 delta_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fieldvalue_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FieldMessage_2eproto;
};
// -------------------------------------------------------------------

class StrFieldList :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:FieldMessage.StrFieldList) */ {
 public:
  StrFieldList();
  virtual ~StrFieldList();

  StrFieldList(const StrFieldList& from);
  StrFieldList(StrFieldList&& from) noexcept
    : StrFieldList() {
    *this = ::std::move(from);
  }

  inline StrFieldList& operator=(const StrFieldList& from) {
    CopyFrom(from);
    return *this;
  }
  inline StrFieldList& operator=(StrFieldList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StrFieldList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StrFieldList* internal_default_instance() {
    return reinterpret_cast<const StrFieldList*>(
               &_StrFieldList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StrFieldList& a, StrFieldList& b) {
    a.Swap(&b);
  }
  inline void Swap(StrFieldList* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StrFieldList* New() const final {
    return CreateMaybeMessage<StrFieldList>(nullptr);
  }

  StrFieldList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StrFieldList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StrFieldList& from);
  void MergeFrom(const StrFieldList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StrFieldList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FieldMessage.StrFieldList";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_FieldMessage_2eproto);
    return ::descriptor_table_FieldMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldListFieldNumber = 1,
  };
  // repeated .FieldMessage.StrField fieldList = 1;
  int fieldlist_size() const;
  private:
  int _internal_fieldlist_size() const;
  public:
  void clear_fieldlist();
  ::FieldMessage::StrField* mutable_fieldlist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::StrField >*
      mutable_fieldlist();
  private:
  const ::FieldMessage::StrField& _internal_fieldlist(int index) const;
  ::FieldMessage::StrField* _internal_add_fieldlist();
  public:
  const ::FieldMessage::StrField& fieldlist(int index) const;
  ::FieldMessage::StrField* add_fieldlist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::StrField >&
      fieldlist() const;

  // @@protoc_insertion_point(class_scope:FieldMessage.StrFieldList)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::StrField > fieldlist_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FieldMessage_2eproto;
};
// -------------------------------------------------------------------

class StrField :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:FieldMessage.StrField) */ {
 public:
  StrField();
  virtual ~StrField();

  StrField(const StrField& from);
  StrField(StrField&& from) noexcept
    : StrField() {
    *this = ::std::move(from);
  }

  inline StrField& operator=(const StrField& from) {
    CopyFrom(from);
    return *this;
  }
  inline StrField& operator=(StrField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const StrField& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StrField* internal_default_instance() {
    return reinterpret_cast<const StrField*>(
               &_StrField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(StrField& a, StrField& b) {
    a.Swap(&b);
  }
  inline void Swap(StrField* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline StrField* New() const final {
    return CreateMaybeMessage<StrField>(nullptr);
  }

  StrField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<StrField>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const StrField& from);
  void MergeFrom(const StrField& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StrField* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "FieldMessage.StrField";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_FieldMessage_2eproto);
    return ::descriptor_table_FieldMessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldValueFieldNumber = 2,
    kDeltaFieldNumber = 1,
  };
  // string fieldValue = 2;
  void clear_fieldvalue();
  const std::string& fieldvalue() const;
  void set_fieldvalue(const std::string& value);
  void set_fieldvalue(std::string&& value);
  void set_fieldvalue(const char* value);
  void set_fieldvalue(const char* value, size_t size);
  std::string* mutable_fieldvalue();
  std::string* release_fieldvalue();
  void set_allocated_fieldvalue(std::string* fieldvalue);
  private:
  const std::string& _internal_fieldvalue() const;
  void _internal_set_fieldvalue(const std::string& value);
  std::string* _internal_mutable_fieldvalue();
  public:

  // uint32 delta = 1;
  void clear_delta();
  ::PROTOBUF_NAMESPACE_ID::uint32 delta() const;
  void set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_delta() const;
  void _internal_set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:FieldMessage.StrField)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fieldvalue_;
  ::PROTOBUF_NAMESPACE_ID::uint32 delta_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_FieldMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IntFieldList

// repeated .FieldMessage.IntField fieldList = 1;
inline int IntFieldList::_internal_fieldlist_size() const {
  return fieldlist_.size();
}
inline int IntFieldList::fieldlist_size() const {
  return _internal_fieldlist_size();
}
inline void IntFieldList::clear_fieldlist() {
  fieldlist_.Clear();
}
inline ::FieldMessage::IntField* IntFieldList::mutable_fieldlist(int index) {
  // @@protoc_insertion_point(field_mutable:FieldMessage.IntFieldList.fieldList)
  return fieldlist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::IntField >*
IntFieldList::mutable_fieldlist() {
  // @@protoc_insertion_point(field_mutable_list:FieldMessage.IntFieldList.fieldList)
  return &fieldlist_;
}
inline const ::FieldMessage::IntField& IntFieldList::_internal_fieldlist(int index) const {
  return fieldlist_.Get(index);
}
inline const ::FieldMessage::IntField& IntFieldList::fieldlist(int index) const {
  // @@protoc_insertion_point(field_get:FieldMessage.IntFieldList.fieldList)
  return _internal_fieldlist(index);
}
inline ::FieldMessage::IntField* IntFieldList::_internal_add_fieldlist() {
  return fieldlist_.Add();
}
inline ::FieldMessage::IntField* IntFieldList::add_fieldlist() {
  // @@protoc_insertion_point(field_add:FieldMessage.IntFieldList.fieldList)
  return _internal_add_fieldlist();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::IntField >&
IntFieldList::fieldlist() const {
  // @@protoc_insertion_point(field_list:FieldMessage.IntFieldList.fieldList)
  return fieldlist_;
}

// -------------------------------------------------------------------

// IntField

// uint32 delta = 1;
inline void IntField::clear_delta() {
  delta_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 IntField::_internal_delta() const {
  return delta_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 IntField::delta() const {
  // @@protoc_insertion_point(field_get:FieldMessage.IntField.delta)
  return _internal_delta();
}
inline void IntField::_internal_set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  delta_ = value;
}
inline void IntField::set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_delta(value);
  // @@protoc_insertion_point(field_set:FieldMessage.IntField.delta)
}

// uint32 fieldValue = 2;
inline void IntField::clear_fieldvalue() {
  fieldvalue_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 IntField::_internal_fieldvalue() const {
  return fieldvalue_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 IntField::fieldvalue() const {
  // @@protoc_insertion_point(field_get:FieldMessage.IntField.fieldValue)
  return _internal_fieldvalue();
}
inline void IntField::_internal_set_fieldvalue(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  fieldvalue_ = value;
}
inline void IntField::set_fieldvalue(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fieldvalue(value);
  // @@protoc_insertion_point(field_set:FieldMessage.IntField.fieldValue)
}

// -------------------------------------------------------------------

// StrFieldList

// repeated .FieldMessage.StrField fieldList = 1;
inline int StrFieldList::_internal_fieldlist_size() const {
  return fieldlist_.size();
}
inline int StrFieldList::fieldlist_size() const {
  return _internal_fieldlist_size();
}
inline void StrFieldList::clear_fieldlist() {
  fieldlist_.Clear();
}
inline ::FieldMessage::StrField* StrFieldList::mutable_fieldlist(int index) {
  // @@protoc_insertion_point(field_mutable:FieldMessage.StrFieldList.fieldList)
  return fieldlist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::StrField >*
StrFieldList::mutable_fieldlist() {
  // @@protoc_insertion_point(field_mutable_list:FieldMessage.StrFieldList.fieldList)
  return &fieldlist_;
}
inline const ::FieldMessage::StrField& StrFieldList::_internal_fieldlist(int index) const {
  return fieldlist_.Get(index);
}
inline const ::FieldMessage::StrField& StrFieldList::fieldlist(int index) const {
  // @@protoc_insertion_point(field_get:FieldMessage.StrFieldList.fieldList)
  return _internal_fieldlist(index);
}
inline ::FieldMessage::StrField* StrFieldList::_internal_add_fieldlist() {
  return fieldlist_.Add();
}
inline ::FieldMessage::StrField* StrFieldList::add_fieldlist() {
  // @@protoc_insertion_point(field_add:FieldMessage.StrFieldList.fieldList)
  return _internal_add_fieldlist();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::FieldMessage::StrField >&
StrFieldList::fieldlist() const {
  // @@protoc_insertion_point(field_list:FieldMessage.StrFieldList.fieldList)
  return fieldlist_;
}

// -------------------------------------------------------------------

// StrField

// uint32 delta = 1;
inline void StrField::clear_delta() {
  delta_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 StrField::_internal_delta() const {
  return delta_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 StrField::delta() const {
  // @@protoc_insertion_point(field_get:FieldMessage.StrField.delta)
  return _internal_delta();
}
inline void StrField::_internal_set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  delta_ = value;
}
inline void StrField::set_delta(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_delta(value);
  // @@protoc_insertion_point(field_set:FieldMessage.StrField.delta)
}

// string fieldValue = 2;
inline void StrField::clear_fieldvalue() {
  fieldvalue_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& StrField::fieldvalue() const {
  // @@protoc_insertion_point(field_get:FieldMessage.StrField.fieldValue)
  return _internal_fieldvalue();
}
inline void StrField::set_fieldvalue(const std::string& value) {
  _internal_set_fieldvalue(value);
  // @@protoc_insertion_point(field_set:FieldMessage.StrField.fieldValue)
}
inline std::string* StrField::mutable_fieldvalue() {
  // @@protoc_insertion_point(field_mutable:FieldMessage.StrField.fieldValue)
  return _internal_mutable_fieldvalue();
}
inline const std::string& StrField::_internal_fieldvalue() const {
  return fieldvalue_.GetNoArena();
}
inline void StrField::_internal_set_fieldvalue(const std::string& value) {
  
  fieldvalue_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void StrField::set_fieldvalue(std::string&& value) {
  
  fieldvalue_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:FieldMessage.StrField.fieldValue)
}
inline void StrField::set_fieldvalue(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fieldvalue_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:FieldMessage.StrField.fieldValue)
}
inline void StrField::set_fieldvalue(const char* value, size_t size) {
  
  fieldvalue_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:FieldMessage.StrField.fieldValue)
}
inline std::string* StrField::_internal_mutable_fieldvalue() {
  
  return fieldvalue_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* StrField::release_fieldvalue() {
  // @@protoc_insertion_point(field_release:FieldMessage.StrField.fieldValue)
  
  return fieldvalue_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void StrField::set_allocated_fieldvalue(std::string* fieldvalue) {
  if (fieldvalue != nullptr) {
    
  } else {
    
  }
  fieldvalue_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fieldvalue);
  // @@protoc_insertion_point(field_set_allocated:FieldMessage.StrField.fieldValue)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace FieldMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_FieldMessage_2eproto
