// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RpcMessage.proto
#ifndef GRPC_RpcMessage_2eproto__INCLUDED
#define GRPC_RpcMessage_2eproto__INCLUDED

#include "RpcMessage.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Message {

// The greeting service definition.
class TSDB final {
 public:
  static constexpr char const* service_full_name() {
    return "Message.TSDB";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // set in the tsdb
    virtual ::grpc::Status TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::Message::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>> AsyncTsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>>(AsyncTsSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>> PrepareAsyncTsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>>(PrepareAsyncTsSetRaw(context, request, cq));
    }
    // get from the tsdb
    virtual ::grpc::Status TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::Message::MessageEntry* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>> AsyncTsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>>(AsyncTsGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>> PrepareAsyncTsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>>(PrepareAsyncTsGetRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // set in the tsdb
      virtual void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // get from the tsdb
      virtual void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>* AsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Message::Reply>* PrepareAsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>* AsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Message::MessageEntry>* PrepareAsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::Message::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::Reply>> AsyncTsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::Reply>>(AsyncTsSetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::Reply>> PrepareAsyncTsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::Reply>>(PrepareAsyncTsSetRaw(context, request, cq));
    }
    ::grpc::Status TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::Message::MessageEntry* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>> AsyncTsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>>(AsyncTsGetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>> PrepareAsyncTsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>>(PrepareAsyncTsGetRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, std::function<void(::grpc::Status)>) override;
      void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)>) override;
      void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Message::Reply>* AsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Message::Reply>* PrepareAsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>* AsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>* PrepareAsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TsSet_;
    const ::grpc::internal::RpcMethod rpcmethod_TsGet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // set in the tsdb
    virtual ::grpc::Status TsSet(::grpc::ServerContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response);
    // get from the tsdb
    virtual ::grpc::Status TsGet(::grpc::ServerContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TsSet() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTsSet(::grpc::ServerContext* context, ::Message::MessageEntry* request, ::grpc::ServerAsyncResponseWriter< ::Message::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TsGet() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTsGet(::grpc::ServerContext* context, ::Message::MessageInfo* request, ::grpc::ServerAsyncResponseWriter< ::Message::MessageEntry>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TsSet<WithAsyncMethod_TsGet<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_TsSet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::Message::MessageEntry, ::Message::Reply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Message::MessageEntry* request, ::Message::Reply* response) { return this->TsSet(context, request, response); }));}
    void SetMessageAllocatorFor_TsSet(
        ::grpc::experimental::MessageAllocator< ::Message::MessageEntry, ::Message::Reply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::Message::MessageEntry, ::Message::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TsSet(
      ::grpc::CallbackServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TsSet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_TsGet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::Message::MessageInfo, ::Message::MessageEntry>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response) { return this->TsGet(context, request, response); }));}
    void SetMessageAllocatorFor_TsGet(
        ::grpc::experimental::MessageAllocator< ::Message::MessageInfo, ::Message::MessageEntry>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::Message::MessageInfo, ::Message::MessageEntry>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TsGet(
      ::grpc::CallbackServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TsGet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_TsSet<ExperimentalWithCallbackMethod_TsGet<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_TsSet<ExperimentalWithCallbackMethod_TsGet<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TsSet() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TsGet() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TsSet() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTsSet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TsGet() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTsGet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_TsSet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TsSet(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TsSet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TsSet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_TsGet() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TsGet(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* TsGet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* TsGet(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TsSet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TsSet() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::Message::MessageEntry, ::Message::Reply>(std::bind(&WithStreamedUnaryMethod_TsSet<BaseClass>::StreamedTsSet, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_TsSet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TsSet(::grpc::ServerContext* /*context*/, const ::Message::MessageEntry* /*request*/, ::Message::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTsSet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Message::MessageEntry,::Message::Reply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TsGet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TsGet() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::Message::MessageInfo, ::Message::MessageEntry>(std::bind(&WithStreamedUnaryMethod_TsGet<BaseClass>::StreamedTsGet, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_TsGet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TsGet(::grpc::ServerContext* /*context*/, const ::Message::MessageInfo* /*request*/, ::Message::MessageEntry* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTsGet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Message::MessageInfo,::Message::MessageEntry>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TsSet<WithStreamedUnaryMethod_TsGet<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TsSet<WithStreamedUnaryMethod_TsGet<Service > > StreamedService;
};

}  // namespace Message


#endif  // GRPC_RpcMessage_2eproto__INCLUDED
