// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RpcMessage.proto

#include "RpcMessage.pb.h"
#include "RpcMessage.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Message {

static const char* TSDB_method_names[] = {
  "/Message.TSDB/TsSet",
  "/Message.TSDB/TsGet",
};

std::unique_ptr< TSDB::Stub> TSDB::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TSDB::Stub> stub(new TSDB::Stub(channel));
  return stub;
}

TSDB::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_TsSet_(TSDB_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TsGet_(TSDB_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TSDB::Stub::TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::Message::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TsSet_, context, request, response);
}

void TSDB::Stub::experimental_async::TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TsSet_, context, request, response, std::move(f));
}

void TSDB::Stub::experimental_async::TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TsSet_, context, request, response, std::move(f));
}

void TSDB::Stub::experimental_async::TsSet(::grpc::ClientContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TsSet_, context, request, response, reactor);
}

void TSDB::Stub::experimental_async::TsSet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TsSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Message::Reply>* TSDB::Stub::AsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Message::Reply>::Create(channel_.get(), cq, rpcmethod_TsSet_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Message::Reply>* TSDB::Stub::PrepareAsyncTsSetRaw(::grpc::ClientContext* context, const ::Message::MessageEntry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Message::Reply>::Create(channel_.get(), cq, rpcmethod_TsSet_, context, request, false);
}

::grpc::Status TSDB::Stub::TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::Message::MessageEntry* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TsGet_, context, request, response);
}

void TSDB::Stub::experimental_async::TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TsGet_, context, request, response, std::move(f));
}

void TSDB::Stub::experimental_async::TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TsGet_, context, request, response, std::move(f));
}

void TSDB::Stub::experimental_async::TsGet(::grpc::ClientContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TsGet_, context, request, response, reactor);
}

void TSDB::Stub::experimental_async::TsGet(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::Message::MessageEntry* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TsGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>* TSDB::Stub::AsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Message::MessageEntry>::Create(channel_.get(), cq, rpcmethod_TsGet_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::Message::MessageEntry>* TSDB::Stub::PrepareAsyncTsGetRaw(::grpc::ClientContext* context, const ::Message::MessageInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::Message::MessageEntry>::Create(channel_.get(), cq, rpcmethod_TsGet_, context, request, false);
}

TSDB::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TSDB_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TSDB::Service, ::Message::MessageEntry, ::Message::Reply>(
          std::mem_fn(&TSDB::Service::TsSet), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TSDB_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TSDB::Service, ::Message::MessageInfo, ::Message::MessageEntry>(
          std::mem_fn(&TSDB::Service::TsGet), this)));
}

TSDB::Service::~Service() {
}

::grpc::Status TSDB::Service::TsSet(::grpc::ServerContext* context, const ::Message::MessageEntry* request, ::Message::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TSDB::Service::TsGet(::grpc::ServerContext* context, const ::Message::MessageInfo* request, ::Message::MessageEntry* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Message

